{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple-api-k8s.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simple-api-k8s.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
